---
- hosts: all

  vars:
    # Apache vars
    apache_remove_default_vhost: true
    apache_create_vhosts: true
    apache_vhosts:
    - servername: "default_vhost"
      documentroot: "/data/www"
      extra_parameters: |
        <Directory "/data/www">
          Options Indexes FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
        </Directory>
 
    # PHP vars
    php_enable_webserver: true
    php_webserver_daemon: "apache2"
    php_packages:
      - libapache2-mod-php7.0
      - php7.0-common
      - php7.0-cli
      - php7.0-dev
      - php7.0-gd
      - php7.0-curl
      - php7.0-imap
      - php7.0-json
      - php7.0-xml
      - php7.0-mbstring
      - php-sqlite3
      - php7.0-mcrypt 
      - php7.0-fileinfo 
      - php7.0-mysql 
      - php7.0-pdo 

  tasks:
  - apt_repository:
      repo: 'ppa:ondrej/php'

  roles:
  - geerlingguy.apache
  - geerlingguy.php