---
- hosts: all

  tasks:
  - apt_repository:
    repo: 'ppa:ondrej/php'

  - name: Install required softwares
    apt: name={{ item }} state=present
    sudo: yes
    with_items:
      - apache2
      - php7.0
      - php7.0-mysql
      - php7.0-gd
