---
- hosts: all

  vars:
    # Apache vars
    apache_remove_default_vhost: true
    apache_create_vhosts: true
    apache_vhosts:
    - servername: "default_vhost"
      documentroot: "/data/www"
      extra_parameters: |
        <Directory "/data/www">
          Options Indexes FollowSymLinks MultiViews
          AllowOverride All
          Require all granted
        </Directory>
 

  tasks:
  - apt_repository:
      repo: 'ppa:ondrej/php'

  roles:
  - geerlingguy.apache