---
- src: geerlingguy.apache
- src: geerlingguy.php
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.composer
- src: geerlingguy.mysql
- src: geerlingguy.nodejs
- src: yatesr.timezone
- src: angstwad.docker_ubuntu
- src: viasite-ansible.zsh
